variables:
  GIT_SUBMODULE_STRATEGY: recursive
  K8S_PLAYGROUND_ROLE: k8s:v1/app-play1/namespace/threat-research/role/deployer
  K8S_GSTAGING_ROLE: k8s:v1/kube-wicket-iad10/namespace/tr-st-deploy/role/deployer
  DOCKER_ROLE: docker:v1/registry/prefix/threat-research
  K8_DEPLOYER_CONTAINER: docker.repo.splunkdev.net/threat-research/k8-deployer
  SMOKETEST_RUNNER: docker.repo.splunkdev.net/threat-research/smoketest-runner
  SRCBRANCH: $CI_COMMIT_REF_NAME

stages:
  - publish_smoketest_runner
  - publish_deployer
  - smoketest_staging


publish_deployer:
  stage: publish_deployer
  image: docker.repo.splunkdev.net/ci-cd/ci-container:alpine-3.11
  before_script:
    - apk add --update docker
  script:
    - eval $(go-go vault -a ${DOCKER_ROLE})
    - cd bin/ssa-end-to-end-testing/k8s-deployer
    - docker build . -t ${K8_DEPLOYER_CONTAINER}:${CI_COMMIT_SHORT_SHA}
    - docker push ${K8_DEPLOYER_CONTAINER}:${CI_COMMIT_SHORT_SHA}
  only:
    - /^ssa.*$/
    - develop

publish_smoketest_runner:
  stage: publish_smoketest_runner
  image: docker.repo.splunkdev.net/ci-cd/ci-container:alpine-3.11
  before_script:
    - apk add --update docker
  script:
    - eval $(go-go vault -a ${DOCKER_ROLE})
    - docker build bin/ssa-end-to-end-testing/smoke-test-runner -t ${SMOKETEST_RUNNER}:${CI_COMMIT_SHORT_SHA} --build-arg SRCBRANCH=$CI_COMMIT_REF_NAME
    - docker push ${SMOKETEST_RUNNER}:${CI_COMMIT_SHORT_SHA}
  only:
    - /^ssa.*$/
    - develop

smoketest_staging:
  stage: smoketest_staging
  resource_group: staging
  dependencies:
    - publish_smoketest_runner
    - publish_deployer
  image: ${K8_DEPLOYER_CONTAINER}:${CI_COMMIT_SHORT_SHA}
  script:
    - eval $(go-go vault -a ${K8S_GSTAGING_ROLE})
    - eval $(go-go vault -a ${DOCKER_ROLE})
    - cd /deployer/k8s
    - ./deployer.sh
    - ./check_deploy_status.sh
  variables:
    SCSENV: app_gstaging1
    SMOKETEST_RUNNER_IMAGE: ${SMOKETEST_RUNNER}:${CI_COMMIT_SHORT_SHA}
  only:
    - /^ssa.*$/
    - develop
